# Generated by Django 3.2 on 2022-08-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='crafts',
            options={'verbose_name_plural': 'Crafts'},
        ),
        migrations.RemoveField(
            model_name='crafts',
            name='image_url',
        ),
        migrations.AddField(
            model_name='crafts',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
