# Generated by Django 3.2 on 2022-08-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts', '0003_category_friendly_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='crafts',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
